package tests;

import org.junit.Assert;
import org.junit.Test;
import org.openqa.selenium.WindowType;
import utilities.TestBase;

public class Day08_WindowHandle2 extends TestBase {
    /*
    TestBase
    Utility class
    There is before and after methods in this class
    Our test base is abstract so we just extend and use the methods
    This kind of utility classes makes the actual test classes short and clean
            Iframes
    Iframe is used to add page within a page, maps, videos, scrollbars,…
    Driver must switch to iframe first to see the elements in the frame
driver.switchTo().frame(“by using id/name, index, or web-element”);-> get in
driver.switchTo().parentFrame() or defaultContent()
    Multiple windows
    The multiple windows may open when there is a link that opens in a new TAB or WINDOWS
    We use windowHandle to get the current window id, windowHandles to get all open windows ids
    We use set of list to get all window ids and switch to the desired window using loop and if condition
            Alerts
    Alerts are generated by javascript alerts. For example when clicking a button, we can see informative alerts
    When there is an alert, we must handle it first to continue the test execution.
    We cannot inspect alerts, but we can handle alerts by switching them first
driver.switchTo().alert().  —-accept(), dissmiss(), getText(), and sendKeys()——
    Collapse

     */

@Test
    public void newWindowTest() throws InterruptedException {

    //open techproeducation on window 1

    driver.get("https://www.techproeducation.com");

    String techProTitle = driver.getTitle();
    Assert.assertTrue(techProTitle.contains("Techpro Education"));

    String techProHandle = driver.getWindowHandle();// getting window 1 id

    Thread.sleep(2000);

    //open amazon on a new window 2

    driver.switchTo().newWindow(WindowType.WINDOW); //creates a new window and switches to that window automatically
    driver.get("https://www.amazon.ca");

    String amazonTitle = driver.getTitle();
    Assert.assertTrue(amazonTitle.contains("Amazon"));

    String amazonHandle = driver.getWindowHandle(); // getting window 2 id

    Thread.sleep(2000);


    //open linkedin

    driver.switchTo().newWindow(WindowType.WINDOW); //creates a new window and switches to that window automatically
    driver.get("https://www.linkedin.com");

    String linkedinTitle = driver.getTitle();
    Assert.assertTrue(linkedinTitle.contains("LinkedIn"));

    String linkedinHandle = driver.getWindowHandle(); // getting window 3 id

    Thread.sleep(2000);

    //Switch back to Techpro
    driver.switchTo().window(techProHandle);
    System.out.println("TechPro : "+driver.getCurrentUrl());

    Thread.sleep(2000);

    //Switch back to amazon
    driver.switchTo().window(amazonHandle);
    System.out.println("Amazon : "+driver.getCurrentUrl());

    Thread.sleep(2000);

    //switch back to linkedin
    driver.switchTo().window(linkedinHandle);
    System.out.println("lnkedin : "+ driver.getCurrentUrl());


}

    @Test
    public void newTabTest() throws InterruptedException {

        //open techproeducation on window 1

        driver.get("https://www.techproeducation.com");

        String techProTitle = driver.getTitle();
        Assert.assertTrue(techProTitle.contains("Techpro Education"));

        String techProHandle = driver.getWindowHandle();// getting TAB 1 id

        Thread.sleep(2000);

        //open amazon on a new window 2

        driver.switchTo().newWindow(WindowType.TAB); //creates a new TAB and switches to that TAB automatically
        driver.get("https://www.amazon.ca");

        String amazonTitle = driver.getTitle();
        Assert.assertTrue(amazonTitle.contains("Amazon"));

        String amazonHandle = driver.getWindowHandle(); // getting TAB 2 id

        Thread.sleep(2000);


        //open linkedin

        driver.switchTo().newWindow(WindowType.TAB); //creates a new TAB and switches to that TAB automatically
        driver.get("https://www.linkedin.com");

        String linkedinTitle = driver.getTitle();
        Assert.assertTrue(linkedinTitle.contains("LinkedIn"));

        String linkedinHandle = driver.getWindowHandle(); // getting TAB 3 id

        Thread.sleep(2000);

        //Switch back to Techpro
        driver.switchTo().window(techProHandle);
        System.out.println("TechPro : "+driver.getCurrentUrl());

        Thread.sleep(2000);

        //Switch back to amazon
        driver.switchTo().window(amazonHandle);
        System.out.println("Amazon : "+driver.getCurrentUrl());

        Thread.sleep(2000);

        //switch back to linkedin
        driver.switchTo().window(linkedinHandle);
        System.out.println("lnkedin : "+ driver.getCurrentUrl());

    }














}
