package tests;

import org.junit.Test;
import org.openqa.selenium.Cookie;
import utilities.TestBase;

import java.util.Set;

public class Day09_Cookies extends TestBase {

    /*
    Cookies are temporary data/files that is generated by the browsers.
    It's a way for a website to remember you, your preferences, and your habits online.
     */


//    Method: handleCookies
@Test
public void cookieTest(){
//        -Go to amazon  and automate the tasks:
    driver.get("https://www.amazon.com");

//        1. Find the total number of cookies
    Set<Cookie> allCookies = driver.manage().getCookies();
    int numOfCookies = allCookies.size();
    System.out.println(numOfCookies);


//        2. Print all the cookies
    for (Cookie w: allCookies){
        System.out.println(w);

    }
//        3. Get the cookies by their name
    System.out.println("Cookie named : "+ driver.manage().getCookieNamed("skin"));//entering cookie name and get

//        4. Add new cookie
    Cookie cookie = new Cookie("my-fav-cookie","apple-pie");
    driver.manage().addCookie(cookie);
    Set<Cookie> newCookies = driver.manage().getCookies();
    System.out.println("New number of Cookie ="+newCookies.size());// 1 more than original number of cookie

//        5. Delete cookie by name
    driver.manage().deleteCookieNamed("session-id");
    int lastNumberOfCookies = driver.manage().getCookies().size();
    System.out.println("Last Number of Cookies ===>>> "+lastNumberOfCookies);

//        6. Delete all of the cookies
    driver.manage().deleteAllCookies();
    int finalNumberOfCookies = driver.manage().getCookies().size();
    System.out.println("Final number of cookies :"+ finalNumberOfCookies);
}
}
